required_columns:
  - user_id
  - age
  - gender
  - country
  - urban_rural
  - income_level
  - employment_status
  - education_level
  - relationship_status
  - has_children
  - household_size
  - occupation
  - ethnicity
  - language_preference
  - device_type
  - budgeting_style
  - brand_loyalty_score
  - impulse_buying_score
  - environmental_consciousness
  - health_conscious_shopping
  - travel_frequency
  - hobby_count
  - social_media_influence_score
  - reading_habits
  - exercise_frequency
  - stress_from_financial_decisions
  - overall_stress_level
  - sleep_quality
  - physical_activity_level
  - mental_health_score
  - weekly_purchases
  - monthly_spend
  - average_order_value
  - preferred_payment_method
  - coupon_usage_frequency
  - loyalty_program_member
  - referral_count
  - product_category_preference
  - shopping_time_of_day
  - weekend_shopper
  - impulse_purchases_per_month
  - browse_to_buy_ratio
  - return_frequency
  - return_rate
  - daily_session_time_minutes
  - product_views_per_day
  - ad_views_per_day
  - wishlist_items_count
  - cart_items_average
  - checkout_abandonments_per_month
  - purchase_conversion_rate
  - app_usage_frequency
  - notification_response_rate
  - account_age_months
  - last_purchase_date
  - social_sharing_frequency
  - premium_subscription
  - cart_abandonment_rate
  - review_writing_frequency
dtypes:
  user_id: Int64
  age: Int64
  gender: String
  country: String
  income_level: Float64
  employment_status: String
  education_level: String
  relationship_status: String
  has_children: Boolean
  household_size: Int64
  occupation: String
  ethnicity: String
  language_preference: String
  device_type: String
  budgeting_style: String
  brand_loyalty_score: Int64
  impulse_buying_score: Int64
  environmental_consciousness: Boolean
  health_conscious_shopping: Boolean
  travel_frequency: Int64
  hobby_count: Int64
  social_media_influence_score: Int64
  reading_habits: Int64
  exercise_frequency: Int64
  stress_from_financial_decisions: Int64
  overall_stress_level: Int64
  sleep_quality: Int64
  physical_activity_level: Int64
  mental_health_score: Int64
  weekly_purchases: Int64
  monthly_spend: Float64
  average_order_value: Float64
  preferred_payment_method: String
  coupon_usage_frequency: Int64
  loyalty_program_member: Boolean
  referral_count: String
  product_category_preference: String
  shopping_time_of_day: String
  weekend_shopper: Boolean
  impulse_purchases_per_month: Int64
  browse_to_buy_ratio: Int64
  return_frequency: Int64
  return_rate: Int64
  daily_session_time_minutes: Int64
  product_views_per_day: Int64
  ad_views_per_day: Int64
  wishlist_items_count: Int64
  cart_items_average: Int64
  checkout_abandonments_per_month: Int64
  purchase_conversion_rate: Int64
  app_usage_frequency: Int64
  notification_response_rate: Int64
  account_age_months: Int64
  last_purchase_date: Date
  social_sharing_frequency: Int64
  premium_subscription: Boolean
  cart_abandonment_rate: Int64
  review_writing_frequency: Int64

from-to:
  income_level: annual_income
  travel_frequency: travel_frequency_per_year
  reading_habits: reading_habits_per_month
  stress_from_financial_decisions: stress_from_financial_decisions_level
  sleep_quality: sleep_quality_level
  return_frequency: return_frequency_per_year
  app_usage_frequency: app_usage_frequency_per_week
  social_sharing_frequency: social_sharing_frequency_per_week
  environmental_consciousness: has_environmental_consciousness
  health_conscious_shopping: has_health_conscious_shopping
  weekend_shopper: is_weekend_shopper
  loyalty_program_member: is_loyalty_program_member
  review_writing_frequency: review_writing_frequency_per_year
  exercise_frequency: exercise_frequency_per_week