columns:
  user_id:
    dtype: Int64
    not_null: True
    required: True
    semantic_rules: True
    business_rules: False
  age:
    dtype: Int64
    not_null: True
    required: True
    min: 18
    max: 99
    semantic_rules: False
    business_rules: True
  gender:
    dtype: String
    not_null: True
    required: True
    values: [
      "Male",
      "Female",
      "Non-binary",
      "Other",
    ]
    semantic_rules: False
    business_rules: False
  country:
    dtype: String
    not_null: True
    required: True
    semantic_rules: False
    business_rules: False
  urban_rural:
    dtype: String
    not_null: True
    required: True
    values: [
      "Urban",
      "Rural",
      "Suburban",
    ]
    semantic_rules: False
    business_rules: False
  income_level:
    dtype: Float64
    not_null: True
    required: True
    min: 0.0
    semantic_rules: True
    business_rules: False
    rename: annual_income
  education_level:
    dtype: String
    not_null: True
    required: True
    values: [
      "High School",
      "Bachelor",
      "Master",
      "PhD",
      "Associate Degree",
    ]
    semantic_rules: False
    business_rules: True
  employment_status:
    dtype: String
    not_null: True
    required: True
    values: [
      "Employed",
      "Unemployed",
      "Retired",
      "Student",
      "Self-employed",
    ]
    semantic_rules: True
    business_rules: True
  relationship_status:
    dtype: String
    not_null: True
    required: True
    values: [
      "Single",
      "In a relationship",
      "Married",
      "Divorced",
      "Widowed",
    ]
    semantic_rules: False
    business_rules: True
  has_children:
    dtype: Boolean
    not_null: True
    required: True
    values: [True,False]
    semantic_rules: False
    business_rules: True
  dtype: Int64
  household_size:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
  occupation:
    dtype: String
    not_null: True
    required: True
    values: [
      "Mobile",
      "Desktop",
      "Tablet",
    ]
    semantic_rules: False
    business_rules: True
  ethnicity:
    dtype: String
    not_null: False
    required: True
    values: [
      "African",
      "African American",
      "Caucasian",
      "Asian",
      "Indigebous/Native",
      "Arabic",
      "Jewish",
      "Hispanic",
      "Pacific",
      "Other",
    ]
    semantic_rules: False
    business_rules: True
  language_preference:
    dtype: String
    not_null: False
    required: True
    semantic_rules: False
    business_rules: False
  device_type:
    dtype: String
    not_null: True
    required: True
    values: [
      "Mobile",
      "Desktop",
      "Tablet",
    ]
    semantic_rules: False
    business_rules: True
  budgeting_style:
    dtype: String
    not_null: False
    required: True
    values: [
      "Strict",
      "Moderate",
      "Loose",
    ]
    semantic_rules: False
    business_rules: True
  brand_loyalty_score:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 10
    semantic_rules: False
    business_rules: True
  impulse_buying_score:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 10
    semantic_rules: False
    business_rules: True
  environmental_consciousness:
    dtype: Boolean
    not_null: False
    required: True
    values: [True,False]
    semantic_rules: False
    business_rules: True
    rename: has_environmental_consciousness
  health_conscious_shopping:
    dtype: Boolean
    not_null: False
    required: True
    values: [True,False]
    semantic_rules: False
    business_rules: True
    rename: has_health_conscious_shopping
  travel_frequency:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
    rename: travel_frequency_per_year
  hobby_count:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
  social_media_influence_score:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 10
    semantic_rules: False
    business_rules: True
  reading_habits:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
    rename: reading_habits_per_month
  exercise_frequency:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 7
    semantic_rules: False
    business_rules: True
    rename: exercise_frequency_per_week
  stress_from_financial_decisions:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 10
    semantic_rules: False
    business_rules: True
    rename: stress_from_financial_decisions_level
  overall_stress_level:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 10
    semantic_rules: False
    business_rules: True
  sleep_quality:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 10
    semantic_rules: False
    business_rules: True
    rename: sleep_quality_level
  physical_activity_level:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 10
    semantic_rules: False
    business_rules: True
  mental_health_score:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 10
    semantic_rules: False
    business_rules: True
  weekly_purchases:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
  monthly_spend:
    dtype: Float64
    not_null: True
    required: True
    min: 0.0
    semantic_rules: True
    business_rules: False
  average_order_value:
    dtype: Float64
    not_null: False
    required: True
    min: 0.0
    semantic_rules: True
    business_rules: False
  preferred_payment_method:
    dtype: String
    not_null: True
    required: True
    values: [
      "Credit Card",
      "Debit Card", 
      "Apple Pay", 
      "Google Pay", 
      "PayPal", 
      "Bank Transfer", 
      "Other", 
    ]
    semantic_rules: False
    business_rules: True
  coupon_usage_frequency:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 7
    semantic_rules: False
    business_rules: True
  loyalty_program_member:
    dtype: Boolean
    not_null: False
    required: True
    values: [True,False]
    semantic_rules: False
    business_rules: True
    rename: is_loyalty_program_member
  referral_count:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
  product_category_preference:
    dtype: String
    not_null: True
    required: True
    values: [
      "Groceries",
      "Beauty",
      "Toys",
      "Home & Health",
      "Home & Kitchen",
      "Sports",
      "Electronics",
      "Fashion",
      "Books",
    ]
    semantic_rules: False
    business_rules: True
  shopping_time_of_day:
    dtype: String
    not_null: false
    required: True
    values: [
      "Morning",
      "Afternoon",
      "Evening",
      "Night",
    ]
    semantic_rules: False
    business_rules: True
  weekend_shopper:
    dtype: Boolean
    not_null: False
    required: True
    values: [True,False]
    rename: is_weekend_shopper
  impulse_purchases_per_month:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 31
    semantic_rules: False
    business_rules: True
  browse_to_buy_ratio:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 100
    semantic_rules: False
    business_rules: True
  return_frequency:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 12
    semantic_rules: False
    business_rules: True
    rename: return_frequency_per_year
  return_rate:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 100
    semantic_rules: False
    business_rules: True
  daily_session_time_minutes:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
  product_views_per_day:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
  ad_views_per_day:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
  checkout_abandonments_per_month:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 31
    semantic_rules: False
    business_rules: True
  purchase_conversion_rate:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 100
    semantic_rules: False
    business_rules: True
  app_usage_frequency:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 7
    semantic_rules: False
    business_rules: True
    rename: app_usage_frequency_per_week
  notification_response_rate:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 100
    semantic_rules: False
    business_rules: True
  account_age_months:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    semantic_rules: True
    business_rules: False
  last_purchase_date:
    dtype: Date
    not_null: True
    required: True
    semantic_rules: True
    business_rules: False
  social_sharing_frequency:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 7
    semantic_rules: False
    business_rules: True
    rename: social_sharing_frequency_per_week
  premium_subscription:
    dtype: Boolean
    not_null: True
    required: True
    values: [True,False]
    semantic_rules: False
    business_rules: True
  cart_abandonment_rate:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 100
    semantic_rules: False
    business_rules: True
  review_writing_frequency:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 12
    semantic_rules: False
    business_rules: True
    rename: review_writing_frequency_per_year
