columns:
  brand_loyalty_score_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  impulse_buying_score_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  social_media_influence_score_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  exercise_frequency_per_week_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  stress_from_financial_decisions_level_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  overall_stress_level_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  sleep_quality_level_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  physical_activity_level_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  mental_health_score_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  coupon_usage_frequency_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  impulse_purchases_per_month_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  browse_to_buy_ratio_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  return_frequency_per_year_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  return_rate_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  checkout_abandonments_per_month_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  purchase_conversion_rate_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  app_usage_frequency_per_week_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  notification_response_rate_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  social_sharing_frequency_per_year_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  cart_abandonment_rate_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  review_writing_frequency_per_year_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  last_purchase_date_is_future:
    dtype: Boolean
    not_null: True
    required: True
    values: [True,False]
  age_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Jovens Adultos",
      "Início de Carreira",
      "Consolidação de Carreira",
      "Estabilidade Financeira",
      "Próximas da Aposentadoria",
      "Aposentados",
    ]
  annual_income_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Classe E",
      "Classe D",
      "Classe C",
      "Classe B",
      "Classe A",
    ]
  has_children_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Sem Filhos",
      "Com Filhos",
    ]
  household_size_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Mora Sozinho ou Com Poucas Pessoas",
      "Mora com Algumas Pessoas",
      "Mora com Muitas Pessoas",
    ]
  brand_loyalty_score_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Detratores",
      "Neutros",
      "Promotores",
    ]
  impulse_buying_score_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Altamente Ponderados",
      "Criteriosos",
      "Equilibrados",
      "Impulsivos",
      "Altamente Impulsivos",
    ]
  social_media_influence_score_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Não Influenciados",
      "Influenciados",
      "Altamente Influenciados",
    ]
  exercise_frequency_per_week_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Sedentary",
      "Lightly Active",
      "Moderately Active",
      "Highly Active",
    ]
  stress_from_financial_decisions_level_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Despreocupados",
      "Confortáveis",
      "Conscientes",
      "Estressados",
    ]
  overall_stress_level_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Muito Relaxados",
      "Relaxados",
      "Equilibrados",
      "Estressados",
      "Muito Estressados",
    ]
  physical_activity_level_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Atividades Leves",
      "Atividades Moderadas",
      "Atividades Intensas",
      "Atividades Muito Intensas",
    ]
  referral_count_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Raramente Indicam",
      "Ocasionalmente Indicam",
      "Frequentemente Indicam",
      "Defensores da Marca",
    ]
  impulse_purchases_per_month_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Não Impulsivos",
      "Compradores por Impulso Ocasional",
      "Compradores por Impulso Moderado",
      "Compradores por Impulso Frequente",
    ]
  browse_to_buy_ratio_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Navegam Muito Frequentemente",
      "Navegam Casualmente",
      "Consideram Comprar",
      "Compram Intencionalmente",
      "Compram Decisivamente",
    ]
  return_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Retornam Raramente",
      "Retornam Ocasionalmente",
      "Retornam Frequentemente",
      "Retornam Muitas Vezes",
    ]
  purchase_conversion_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Compradores Raros",
      "Compradores Ocasionais",
      "Compradores em Potencial",
      "Compradores Frequentes",
    ]
  premium_subscription_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Plano Premium",
      "Plano Gratuito",
    ]
  app_usage_frequency_per_week_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Pouco Ativo",
      "Moderadamente Ativo",
      "Muito Ativo",
    ]
  notification_response_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Raramente Responsivos",
      "Ocasionalmente Responsivos",
      "Responsivos",
      "Muito Responsivos",
    ]
  social_sharing_frequency_per_year_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Raramente",
      "Ocasionalmente",
      "Frequentemente",
      "Sempre",
    ]
  cart_abandonment_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Rare Abandoner",
      "Occasional Abandoner",
      "Frequent Abandoner",
      "Heavy Abandoner",
    ]
  review_writing_frequency_per_year_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Contribuidores Raros",
      "Contribuidores Ocasionais",
      "Contribuidores Frequentes",
      "Contribuidores Poderosos",
    ]
  gender:
    dtype: String
    not_null: True
    required: True
    values: [
      "Masculino",
      "Feminino",
      "Não Binário",
      "Outro",
    ]
  urban_rural:
    dtype: String
    not_null: True
    required: True
    values: [
      "Urbano",
      "Rural",
      "Suburbano",
    ]
  education_level:
    dtype: String
    not_null: True
    required: True
    values: [
      "Ensino Médio",
      "Bacharel",
      "Mestre",
      "Doutor",
      "Associado",
    ]
  shopping_time_of_day:
    dtype: String
    not_null: True
    required: True
    values: [
      "Manhã",
      "Tarde",
      "Noite",
      "Madrugada",
    ]
  employment_status:
    dtype: String
    not_null: True
    required: True
    values: [
      "Empregado",
      "Desempregado",
      "Aposentado",
      "Estudante",
      "Autônomo",
    ]
  relationship_status:
    dtype: String
    not_null: True
    required: True
    values: [
      "Solteiro(a)",
      "Em um Relacionamento",
      "Casado(a)",
      "Divorciado(a)",
      "Viúvo(a)",
    ]
  preferred_payment_method:
    dtype: String
    not_null: True
    required: True
    values: [
      "Cartão de Crédito",
      "Cartão de Débito",
      "Apple Pay",
      "Google Pay",
      "PayPal",
      "Transferência Bancária",
    ]
  product_category_preference:
    dtype: String
    not_null: True
    required: True
    values: [
      "Alimentos",
      "Beleza",
      "Brinquedos",
      "Casa e Saúde",
      "Casa e Cozinha", 
      "Esportes",
      "Eletrônicos",
      "Moda",
      "Livros",
    ]