columns:
  user_id:
    dtype: Int64
    not_null: True
    required: True
  age:
    dtype: Int64
    not_null: True
    required: True
    min: 18
    max: 99
  gender:
    dtype: String
    not_null: True
    required: True
    values: [
      "Male",
      "Female",
      "Non-binary",
      "Other",
    ]
  country:
    dtype: String
    not_null: True
    required: True
  urban_rural:
    dtype: String
    not_null: True
    required: True
    values: [
      "Urban",
      "Rural",
      "Suburban",
    ]
  annual_income:
    dtype: Float64
    not_null: True
    required: True
  education_level:
    dtype: String
    not_null: True
    required: True
    values: [
      "High School",
      "Bachelor",
      "Master",
      "PhD",
      "Associate Degree",
    ]
  employment_status:
    dtype: String
    not_null: True
    required: True
    values: [
      "Employed",
      "Unemployed",
      "Retired",
      "Student",
      "Self-employed",
    ]
  relationship_status:
    dtype: String
    not_null: True
    required: True
    values: [
      "Single",
      "In a relationship",
      "Married",
      "Divorced",
      "Widowed",
    ]
  has_children:
    dtype: Boolean
    not_null: True
    required: True
    values: [True,False]
  dtype: Int64
  household_size:
    dtype: Int64
    not_null: True
    required: True
  occupation:
    dtype: String
    not_null: True
    required: True
  ethnicity:
    dtype: String
    not_null: False
    required: True
    values: [
      "African",
      "African American",
      "Caucasian",
      "Asian",
      "Indigebous/Native",
      "Arabic",
      "Jewish",
      "Hispanic",
      "Pacific",
      "Other",
    ]
  language_preference:
    dtype: String
    not_null: False
    required: True
  device_type:
    dtype: String
    not_null: True
    required: True
    values: [
      "Mobile",
      "Desktop",
      "Tablet",
    ]
  budgeting_style:
    dtype: String
    not_null: False
    required: True
    values: [
      "Strict",
      "Moderate",
      "Loose",
    ]
  brand_loyalty_score:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  impulse_buying_score:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  has_environmental_consciousness:
    dtype: Boolean
    not_null: False
    required: True
    values: [True,False]
  has_health_conscious_shopping:
    dtype: Boolean
    not_null: False
    required: True
    values: [True,False]
  travel_frequency_per_year:
    dtype: Int64
    not_null: False
    required: True
  hobby_count:
    dtype: Int64
    not_null: False
    required: True
  social_media_influence_score:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  reading_habits_per_month:
    dtype: Int64
    not_null: False
    required: True
  exercise_frequency_per_week:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  stress_from_financial_decisions_level:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  overall_stress_level:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  sleep_quality_level:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  physical_activity_level:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  mental_health_score:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  weekly_purchases:
    dtype: Int64
    not_null: True
    required: True
  monthly_spend:
    dtype: Float64
    not_null: True
    required: True
  average_order_value:
    dtype: Float64
    not_null: False
    required: True
  preferred_payment_method:
    dtype: String
    not_null: True
    required: True
    values: [
      "Credit Card",
      "Debit Card", 
      "Apple Pay", 
      "Google Pay", 
      "PayPal", 
      "Bank Transfer", 
      "Other", 
    ]
  coupon_usage_frequency:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  is_loyalty_program_member:
    dtype: Boolean
    not_null: False
    required: True
    values: [True,False]
  referral_count:
    dtype: Int64
    not_null: True
    required: True
  product_category_preference:
    dtype: String
    not_null: True
    required: True
    values: [
      "Groceries",
      "Beauty",
      "Toys",
      "Home & Health",
      "Home & Kitchen",
      "Sports",
      "Electronics",
      "Fashion",
      "Books",
    ]
  shopping_time_of_day:
    dtype: String
    not_null: false
    required: True
    values: [
      "Morning",
      "Afternoon",
      "Evening",
      "Night",
    ]
  is_weekend_shopper:
    dtype: Boolean
    not_null: False
    required: True
    values: [True,False]
  impulse_purchases_per_month:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  browse_to_buy_ratio:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  return_frequency_per_year:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  return_rate:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  daily_session_time_minutes:
    dtype: Int64
    not_null: True
    required: True
  product_views_per_day:
    dtype: Int64
    not_null: True
    required: True
  ad_views_per_day:
    dtype: Int64
    not_null: False
    required: True
  checkout_abandonments_per_month:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  purchase_conversion_rate:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  app_usage_frequency_per_week:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  notification_response_rate:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  account_age_months:
    dtype: Int64
    not_null: True
    required: True
  last_purchase_date:
    dtype: Date
    not_null: True
    required: True
  social_sharing_frequency_per_year:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  premium_subscription:
    dtype: Boolean
    not_null: True
    required: True
    values: [True,False]
  cart_abandonment_rate:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  review_writing_frequency_per_year:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  last_purchase_date_is_future:
    dtype: Boolean
    not_null: True
    required: True
    values: [True,False]
  age_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Early Adopters",
      "Early Career Professionals",
      "Professional Consolidation",
      "High Financial Stability",
      "Pre-Retirement",
      "Low Digital Adoption",
    ]
  household_size_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Single-person",
      "Small",
      "Medium",
      "Large",
    ]
  brand_loyalty_score_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Detractors",
      "Neutral",
      "Promoters",
    ]
  impulse_buying_score_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Low",
      "Low",
      "Moderate",
      "High",
      "Very High",
    ]
  social_media_influence_score_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Low",
      "Medium",
      "High",
    ]
  exercise_frequency_per_week_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Inactive",
      "Lightly Active",
      "Active",
      "Highly Active",
    ]
  stress_from_financial_decisions_level_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Low",
      "Low",
      "Medium",
      "High",
      "Very High",
    ]
  overall_stress_level_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Low",
      "Low",
      "Medium",
      "High",
      "Very High",
    ]
  physical_activity_level_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Light",
      "Light",
      "Moderate",
      "Heavy",
      "Very Heavy",
    ]
  referral_count_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Non-referrer",
      "Low",
      "Moderate",
      "High",
    ]
  impulse_purchases_per_month_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Non-impulsive",
      "Not Very Impulsive",
      "Moderate",
      "Impulsilve",
    ]
  browse_to_buy_ratio_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Browse a Lot & Buy Little",
      "Low Intention",
      "Undecided",
      "Good Intention",
      "High Intention",
    ]
  return_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Low",
      "Low",
      "Moderate",
      "High",
      "Very High",
    ]
  purchase_conversion_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Low",
      "Low",
      "Moderate",
      "High",
      "Very High",
    ]
  purchase_conversion_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Low",
      "Low",
      "Moderate",
      "High",
      "Very High",
    ]
  app_usage_frequency_per_week_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Low",
      "Moderate",
      "High",
    ]
  notification_response_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Low",
      "Low",
      "Moderate",
      "High",
      "Very High",
    ]
  social_sharing_frequency_per_year_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Low",
      "Moderate",
      "High",
    ]
  cart_abandonment_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Low",
      "Low",
      "Moderate",
      "High",
      "Very High",
    ]
  review_writing_frequency_per_year_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Other",
      "Very Low",
      "Low",
      "Moderate",
      "High",
      "Very High",
    ]