stress_from_financial_decisions_level:
  rules: range
  min: 0  
  max: 10
sleep_quality_level:
  rules: range
  min: 0  
  max: 10
physical_activity_level:
  rules: range
  min: 0  
  max: 10
overall_stress_level:
  rules: range
  min: 0  
  max: 10
mental_health_score:
  rules: range
  min: 0  
  max: 10
social_media_influence_score:
  rules: range
  min: 0  
  max: 10
impulse_buying_score:
  rules: range
  min: 0  
  max: 10
brand_loyalty_score:
  rules: range
  min: 0  
  max: 10
browse_to_buy_ratio:
  rules: range
  min: 0  
  max: 100
cart_abandonment_rate:
  rules: range
  min: 0  
  max: 100
notification_response_rate:
  rules: range
  min: 0  
  max: 100
purchase_conversion_rate:
  rules: range
  min: 0  
  max: 100
return_rate:
  rules: range
  min: 0  
  max: 100
exercise_frequency_per_week:
  rules: range
  min: 0  
  max: 7
reading_habits_per_month:
  rules: range
  min: 0  
  max: 31
impulse_purchases_per_month:
  rules: range
  min: 0  
  max: 31
checkout_abandonments_per_month:
  rules: range
  min: 0  
  max: 31
travel_frequency_per_year:
  rules: range
  min: 0
  max: 12
has_children:
  rules: values
  values:
    - False
    - True
has_environmental_consciousness:
  rules: values
  values:
    - False
    - True
has_health_conscious_shopping:
  rules: values
  values:
    - False
    - True
is_weekend_shopper:
  rules: values
  values:
    - False
    - True
is_loyalty_program_member:
  rules: values
  values:
    - False
    - True
gender:
  rules: values
  values:
    - Male
    - Female
    - Non-binary
    - Other
employment_status:
  rules: values
  values:
    - Employed
    - Unemployed
    - Retired
    - Student
    - Self-employed
urban_rural:
  rules: values
  values:
    - Suburban
    - Urban
    - Rural
education_level:
  rules: values
  values:
    - High School
    - Bachelor
    - Master
    - PhD
    - Associate Degree 
relationship_status:
  rules: values
  values:
    - Single
    - In a relationship
    - Married
    - Divorced
    - Widowed
device_type:
  rules: values
  values:
    - Mobile
    - Desktop
    - Tablet
ethnicity:
  rules: values
  values:
    - African
    - African American
    - Caucasian
    - Asian
    - Indigebous/Native
    - Arabic
    - Jewish
    - Hispanic
    - Pacific
    - Other
budgeting_style:
  rules: values
  values:
    - Strict
    - Moderate
    - Loose
preferred_payment_method:
  rules: values
  values:
    - Credit Card
    - Debit Card
    - Apple Pay
    - Google Pay
    - PayPal
    - Bank Transfer
    - Other
product_category_preference:
  rules: values
  values:
    - Groceries
    - Beauty
    - Toys
    - Home & Health
    - Home & Kitchen
    - Sports
    - Electronics
    - Fashion
    - Books
shopping_time_of_day:
  rules: values
  values:
    - Morning
    - Afternoon
    - Evening
    - Night

