data:
  ingestion:
    origin: "dhrubangtalukdar/e-commerce-shopper-behavior-amazonshopify-based"
    destination: "data/raw/data.parquet"
  bronze:
    origin: "data/raw/data.parquet"
    destination: "data/bronze/data.parquet"
  silver:
    parent: "data/silver/"
    origin: "data/bronze/data.parquet"
    destination: "data/silver/data.parquet"
  gold:
    origin: "data/silver/data.parquet"
    destination: "data/gold/data.csv"
