from enum import Enum


class ErrorCode(Enum):
    DUPLICATED_USER_ID = 0
    FUTURE_DATE = 1
    MIN_VALUE_VIOLATION = 2
    UNEMPLOYED_WITH_INCOME = 3
    EMPLOYED_WITHOUT_INCOME = 4
    RETIRED_WITHOUT_INCOME = 5
    SELF_EMPLOYED_WITHOUT_INCOME = 6
