columns:
  user_id:
    not_null: True
    required: True
  age:
    not_null: True
    required: True
    min: 18
    max: 99
  gender:
    not_null: True
    required: True
    values: ["Male","Female","Non-binary","Other",]
  country:
    not_null: True
    required: True
  urban_rural:
    not_null: True
    required: True
    values: ["Urban","Rural","Suburban",]
  income_level:
    not_null: True
    required: True
    min: 0.0
  employment_status:
    not_null: True
    required: True
    values: ["Employed","Unemployed","Retired","Student","Self-employed",]
  relationship_status:
    not_null: True
    required: True
    values: ["Single","In a relationship","Married","Divorced","Widowed",]
  has_children:
    not_null: True
    required: True
    values: [True,False]
  household_size:
    not_null: True
    required: True
    min: 0
  occupation:
    not_null: True
    required: True
    values: ["Mobile","Desktop","Tablet",]
  ethnicity:
    not_null: False
    required: True
    values: [
      "African",
      "African American",
      "Caucasian",
      "Asian",
      "Indigebous/Native",
      "Arabic",
      "Jewish",
      "Hispanic",
      "Pacific",
      "Other",
    ]
  language_preference:
    not_null: False
    required: True
  device_type:
    not_null: True
    required: True
    values: ["Mobile","Desktop","Tablet",]
  budgeting_style:
    not_null: False
    required: True
    values: ["Strict","Moderate","Loose",]
  brand_loyalty_score:
    not_null: True
    required: True
    min: 0
    max: 10
  impulse_buying_score:
    not_null: False
    required: True
    min: 0
    max: 10
  environmental_consciousness:
    not_null: False
    required: True
    values: [True,False]
  health_conscious_shopping:
    not_null: False
    required: True
    values: [True,False]
  travel_frequency:
    not_null: False
    required: True
    min: 0
  hobby_count:
    not_null: False
    required: True
    min: 0
  social_media_influence_score:
    not_null: False
    required: True
    min: 0
    max: 10
  reading_habits:
    not_null: False
    required: True
    min: 0
  exercise_frequency:
    not_null: False
    required: True
    min: 0
    max: 7
  stress_from_financial_decisions:
    not_null: False
    required: True
    min: 0
    max: 10
  overall_stress_level:
    not_null: False
    required: True
    min: 0
    max: 10
  sleep_quality:
    not_null: False
    required: True
    min: 0
    max: 10
  physical_activity_level:
    not_null: False
    required: True
    min: 0
    max: 10
  mental_health_score:
    not_null: False
    required: True
    min: 0
    max: 10
  weekly_purchases:
    not_null: True
    required: True
    min: 0
  monthly_spend:
    not_null: True
    required: True
    min: 0.0
  average_order_value:
    not_null: False
    required: True
    min: 0
  preferred_payment_method:
    not_null: True
    required: True
    values: [
      "Credit Card",
      "Debit Card", 
      "Apple Pay", 
      "Google Pay", 
      "PayPal", 
      "Bank Transfer", 
      "Other", 
    ]
  coupon_usage_frequency:
    not_null: True
    required: True
    min: 0
    max: 7
  loyalty_program_member:
    not_null: False
    required: True
    values: [True,False]
  referral_count:
    not_null: True
    required: True
    min: 0
  product_category_preference:
    not_null: True
    required: True
    values: [
      "Groceries",
      "Beauty",
      "Toys",
      "Home & Health",
      "Home & Kitchen",
      "Sports",
      "Electronics",
      "Fashion",
      "Books",
    ]
  shopping_time_of_day:
    not_null: false
    required: True
    values: [
      "Morning",
      "Afternoon",
      "Evening",
      "Night",
    ]
  weekend_shopper:
    not_null: False
    required: True
    values: [True,False]
  impulse_purchases_per_month:
    not_null: True
    required: True
    min: 0
    max: 31
  browse_to_buy_ratio:
    not_null: False
    required: True
    min: 0
    max: 100
  return_frequency:
    not_null: True
    required: True
    min: 0
    max: 12
  return_rate:
    not_null: True
    required: True
    min: 0
    max: 100
  daily_session_time_minutes:
    not_null: True
    required: True
    min: 0
  product_views_per_day:
    not_null: True
    required: True
    min: 0
  ad_views_per_day:
    not_null: False
    required: True
    min: 0
  checkout_abandonments_per_month:
    not_null: True
    required: True
    min: 0
    max: 31
  purchase_conversion_rate:
    not_null: True
    required: True
    min: 0
    max: 100
  app_usage_frequency:
    not_null: True
    required: True
    min: 0
    max: 7
  notification_response_rate:
    not_null: True
    required: True
    min: 0
    max: 100
  account_age_months:
    not_null: True
    required: True
    min: 0
  last_purchase_date:
    not_null: True
    required: True
  social_sharing_frequency:
    not_null: False
    required: True
    min: 0
    max: 7
  premium_subscription:
    not_null: True
    required: True
    values: [True,False]
  cart_abandonment_rate:
    not_null: True
    required: True
    min: 0
    max: 100
  review_writing_frequency:
    not_null: False
    required: True
    min: 0
    max: 12
